name = input("Name? ")
print("Hello " + name)
name = input("Name? ")
print("Hello " + name)
age = input("Age? ")
addr = input("City? ")
print(name + " lives in " + addr)
year = 2026 - int(age)
print("Born in: " + str(year))
pyear = 2026 - int(age)
print("Born in: " + str(year))
